<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="//cdn.weatherapi.com/weather-widget/weather.css"
      type="text/css"
      media="all"
    />
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149630039-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      gtag('config', 'UA-149630039-1');
    </script>

    <title>Document</title>
  </head>
  <body>
    <aside id="weatherapiweatherwidget-2" class="widget widget_weatherapiweatherwidget">
      <div
        id="weatherapi-weather-london-city-of-london-greater-london-united-kingdom"
        class="weatherapi-weather-wrap awecf awe_wide awe_without_stats awe-code-1183 awe-desc-rain shm_4 scheme_41"
      >
        <div class="weatherapi-weather-cover">
          <div class="weatherapi-weather-todays-stats-location">
            <div class="awe_desc">Ha Noi</div>
          </div>
          <div class="weatherapi-weather-todays-stats-big-pict">
            <img
              src="//cdn.weatherapi.com/weather/128x128/day/143.png"
              alt="Weather is Mist"
              title="Weather is Mist"
            /><span class="weatherapi_descr">Mist</span>
          </div>
          <!-- /.weatherapi-weather-todays-stats -->
          <div class="weatherapi-weather-todays-stats-location">
            <div class="weatherapi_descr">Wind: 6.8 kmph</div>
            <span class="weatherapi_descr">Precip: 0.10 mm</span>
            <div class="awe_desc">Pressure: 1016.0 mb</div>
          </div>
          <!-- location -->
          <div class="weatherapi-weather-current-temp">21.0<span> &deg;c</span></div>
          <!-- /.weatherapi-weather-current-temp -->
          <div class="weatherapi-weather-forecast awe_days_5 awecf">
            <div class="weatherapi-weather-forecast-day">
              <div class="weatherapi-weather-forecast-day-abbr">Thu</div>
              <div class="weatherapi-weather-forecast-day-abbr">
                <div class="">
                  <img
                    src="//cdn.weatherapi.com/weather/64x64/day/302.png"
                    alt="Moderate rain"
                    title="Moderate rain"
                  />
                </div>
                <!-- /.weatherapi-weather-todays-stats -->
              </div>
              <div class="weatherapi-weather-forecast-day-temp">25.8<span> &deg;c</span></div>
            </div>

            <div class="weatherapi-weather-forecast-day">
              <div class="weatherapi-weather-forecast-day-abbr">Fri</div>
              <div class="weatherapi-weather-forecast-day-abbr">
                <div class="">
                  <img
                    src="//cdn.weatherapi.com/weather/64x64/day/176.png"
                    alt="Patchy rain possible"
                    title="Patchy rain possible"
                  />
                </div>
                <!-- /.weatherapi-weather-todays-stats -->
              </div>
              <div class="weatherapi-weather-forecast-day-temp">20.1<span> &deg;c</span></div>
            </div>

            <div class="weatherapi-weather-forecast-day">
              <div class="weatherapi-weather-forecast-day-abbr">Sat</div>
              <div class="weatherapi-weather-forecast-day-abbr">
                <div class="">
                  <img
                    src="//cdn.weatherapi.com/weather/64x64/day/119.png"
                    alt="Cloudy"
                    title="Cloudy"
                  />
                </div>
                <!-- /.weatherapi-weather-todays-stats -->
              </div>
              <div class="weatherapi-weather-forecast-day-temp">18.6<span> &deg;c</span></div>
            </div>

            <div class="weatherapi-weather-forecast-day">
              <div class="weatherapi-weather-forecast-day-abbr">Sun</div>
              <div class="weatherapi-weather-forecast-day-abbr">
                <div class="">
                  <img
                    src="//cdn.weatherapi.com/weather/64x64/day/113.png"
                    alt="Sunny"
                    title="Sunny"
                  />
                </div>
                <!-- /.weatherapi-weather-todays-stats -->
              </div>
              <div class="weatherapi-weather-forecast-day-temp">21.5<span> &deg;c</span></div>
            </div>

            <div class="weatherapi-weather-forecast-day">
              <div class="weatherapi-weather-forecast-day-abbr">Mon</div>
              <div class="weatherapi-weather-forecast-day-abbr">
                <div class="">
                  <img
                    src="//cdn.weatherapi.com/weather/64x64/day/113.png"
                    alt="Sunny"
                    title="Sunny"
                  />
                </div>
                <!-- /.weatherapi-weather-todays-stats -->
              </div>
              <div class="weatherapi-weather-forecast-day-temp">22.4<span> &deg;c</span></div>
            </div>
          </div>
          <div class="weatherapi-weather-more-weather-link">
            <a
              href="https://www.weatherapi.com/weather/q/ha-noi-2717933"
              target="_blank"
              title="Ha Noi weather"
              >weatherapi.com</a
            >
          </div>
        </div>
        <!-- /.weatherapi-weather-cover -->
      </div>
      <!-- /.weatherapi-weather-wrap -->
    </aside>
  </body>
</html>


<!-- <h3>Thời tiết trong ngày</h3>

<div id="weather">
    <div class="top-content">
        <h2>Hà Nội, Việt Nam</h2>
    </div>

    <div class="mid-content">
        <div class="col">
            <div class="image"></div>
            <div class="temperature"></div>
        </div>
        <div class="col">
            <ul class="info"></ul>
        </div>
    </div>
</div>

<script>
    require(['jquery', 'simple_weather'], function ($) {
        $(function () {
            $.simpleWeather({
                location: 'Hanoi, VN',
                woeid: '',
                unit: 'c',
                success: function (weather) {
                    $('.image').html('<img src="' + weather.image + '"/>');
                    $('.temperature').html(weather.temp + '<sup>o</sup>C');

                    var info = '<li>Status: ' + weather.currently + '</li>' +
                        '<li>Range: ' + weather.low + '<sup>o</sup>C - ' + weather.high + '<sup>o</sup>C</li>' +
                        '<li>Wind: ' + weather.wind.speed + ' km/h</li>';
                    $('.info').html(info);
                },
                error: function (error) {
                    $("#weather").html('<p>' + error + '</p>');
                }
            });
        });
    });
</script> -->